# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado Projects/FFT_DMA/FFT_DMA.srcs/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2.xci
# IP: The module: 'Block_design_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado Projects/FFT_DMA/FFT_DMA.srcs/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2.xci
# IP: The module: 'Block_design_rst_ps7_0_50M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Vivado Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_rst_ps7_0_50M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
