# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Block_design/Block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design || ORIG_REF_NAME==Block_design} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_processing_system7_0_1/Block_design_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_processing_system7_0_1 || ORIG_REF_NAME==Block_design_processing_system7_0_1} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axi_dma_0_1/Block_design_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_axi_dma_0_1 || ORIG_REF_NAME==Block_design_axi_dma_0_1} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_ps7_0_axi_periph_2/Block_design_ps7_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_ps7_0_axi_periph_2 || ORIG_REF_NAME==Block_design_ps7_0_axi_periph_2} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_rst_ps7_0_50M_2/Block_design_rst_ps7_0_50M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_rst_ps7_0_50M_2 || ORIG_REF_NAME==Block_design_rst_ps7_0_50M_2} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xbar_1/Block_design_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_xbar_1 || ORIG_REF_NAME==Block_design_xbar_1} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_axi_mem_intercon_2/Block_design_axi_mem_intercon_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_axi_mem_intercon_2 || ORIG_REF_NAME==Block_design_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xfft_0_0/Block_design_xfft_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_xfft_0_0 || ORIG_REF_NAME==Block_design_xfft_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xlconcat_0_0/Block_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_xlconcat_0_0 || ORIG_REF_NAME==Block_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xlconstant_0_0/Block_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_xlconstant_0_0 || ORIG_REF_NAME==Block_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_xlconstant_1_0/Block_design_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_xlconstant_1_0 || ORIG_REF_NAME==Block_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_system_ila_0_0/Block_design_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_system_ila_0_0 || ORIG_REF_NAME==Block_design_system_ila_0_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_0/Block_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_0 || ORIG_REF_NAME==Block_design_auto_pc_0} -quiet] -quiet

# IP: bd/Block_design/ip/Block_design_auto_pc_1/Block_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_design_auto_pc_1 || ORIG_REF_NAME==Block_design_auto_pc_1} -quiet] -quiet

# XDC: d:/Vivado_Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/Block_design_ooc.xdc
