# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado_Projects/FFT_DMA/FFT_DMA.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1/Block_design_xbar_1.xci
# IP: The module: 'Block_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_xbar_1/Block_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Vivado_Projects/FFT_DMA/FFT_DMA.srcs/sources_1/bd/Block_design/ip/Block_design_xbar_1/Block_design_xbar_1.xci
# IP: The module: 'Block_design_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado_Projects/FFT_DMA/FFT_DMA.gen/sources_1/bd/Block_design/ip/Block_design_xbar_1/Block_design_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_design_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
