domain_path: D:\Vitis_Workspaces\DMA-FFT-Workspace\DMA-FFT-noScatter\export\DMA-FFT-noScatter\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
